# Filter a uv/pip-compile style requirements-lock.txt, dropping one or more
# named seed packages (comma-separated in -v exclude=...) and any other
# locked package whose *every* "# via" parent is itself already dropped --
# i.e. packages that exist solely to satisfy an excluded package's own
# dependencies (for example a hidapi-only setuptools build requirement).
# Packages also required by a root requirement or a still-kept package are
# preserved, so unrelated direct/transitive dependencies are never deleted.
#
# Usage: awk -v exclude=hidapi -f filter-lock-exclude.awk requirements-lock.txt

BEGIN {
    split(exclude, seed, ",")
    for (i in seed) excluded[seed[i]] = 1
    block_count = 0
}

function start_block(line,    name) {
    name = line
    sub(/==.*/, "", name)
    block_count++
    names[block_count] = name
    via_n[block_count] = 0
    text[block_count] = line "\n"
}

/^[[:alnum:]_.-]+==/ {
    start_block($0)
    next
}

block_count == 0 {
    # Header comment lines before the first package block (e.g. the
    # "autogenerated by uv" banner).
    preamble = preamble $0 "\n"
    next
}

{
    text[block_count] = text[block_count] $0 "\n"
    if ($0 ~ /^[[:space:]]*# via /) {
        parent = $0
        sub(/^[[:space:]]*# via[[:space:]]*/, "", parent)
        via_n[block_count]++
        via[block_count, via_n[block_count]] = parent
    }
}

END {
    changed = 1
    while (changed) {
        changed = 0
        for (b = 1; b <= block_count; b++) {
            if (names[b] in excluded) continue
            if (via_n[b] == 0) continue  # no via comment: never auto-drop
            keep = 0
            for (i = 1; i <= via_n[b]; i++) {
                if (!(via[b, i] in excluded)) keep = 1
            }
            if (!keep) {
                excluded[names[b]] = 1
                changed = 1
            }
        }
    }
    printf "%s", preamble
    for (b = 1; b <= block_count; b++) {
        if (names[b] in excluded) continue
        n = split(text[b], lines, "\n")
        for (j = 1; j < n; j++) {
            parent = lines[j]
            if (parent ~ /^[[:space:]]*# via /) {
                sub(/^[[:space:]]*# via[[:space:]]*/, "", parent)
                if (parent in excluded) continue
            }
            print lines[j]
        }
    }
}
